project:
  type: website
  output-dir: docs

website:
  title: "Amogh Atwe"
  search: 
    location: navbar
    type: textbox
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: contact.qmd
        text: Contact
  page-footer: 
       left: "This website is hosted by [GitHub Pages](https://pages.github.com/) and made using [Qaurto](https://quarto.org/) - [Light theme](https://bootswatch.com/flatly/) and [Dark theme](https://bootswatch.com/darkly/)."
       right: 
        - icon: github
          href: https://github.com/amoghatwe
        - icon: linkedin
          href: https://www.linkedin.com/in/amogh-atwe/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    fontsize: 1em
    mainfont: Arial
    monofont: SF Mono
