project:
  type: website
  output-dir: docs

website:
  title: "Amogh Atwe // Portfolio"
  search: 
    location: navbar
    type: textbox
  
  page-footer: 
       left: "This website is hosted on [GitHub Pages](https://pages.github.com/) and made using [Qaurto](https://quarto.org/) - [Light theme](https://bootswatch.com/flatly/) and [Dark theme](https://bootswatch.com/darkly/)."
       right: 
        - icon: github
          href: https://github.com/amoghatwe
        - icon: linkedin
          href: https://www.linkedin.com/in/amogh-atwe/

  navbar:
    pinned: true
    search: true
    right:
      - text: About Me
        href: "#about-me"
      - text: Papers
        href: "#papers"
      - text: Projects
        href: "#projects"
      - text: Contact
        href: "#contact-me"
          

format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    fontsize: 1em
    mainfont: Arial
    monofont: SF Mono